### ISSUE TITLE
Option to decide to group/ungroup errors 4xx and 5xx

### ISSUE THREAD

**Issue by PaulaSemaan** [Appdynamics/apigee-monitoring-extension#14]
The idea is to have an option to decide if errors 4xx should be grouped together (same for errors 5xx) or if each status code should be sent on its own.

Currently, all errors 4xx are grouped together, and all errors 5xx are grouped together.

Apigee http status codes: https://docs.apigee.com/api-platform/troubleshoot/http-status-codes

**Comment by stuartgreenshields** [comment]
The more we ungroup, the longer the script takes to run, as it needs to separate APIGEE API calls with code filters for each error. Once a custom extension script type gets above 60 seconds, then that means the script doesn't run at the next interval and AppD will mark all metrics for that missed interval as zero. Therefore, it is critical to keep the script under 60 seconds to execute so not to affect baselines etc. Therefore on testing, I think that we should just break out the key ones and group the rest together like it currently is i.e. 401, 403, other 4xx, 502, 503, 504 and 5xx. keeping the number of filter down means the script should have plenty of time to execute and complete every 60 seconds, unless contacting the APIGEE or the APOGEE is slowing down in response to the API call for their analytics.
